package(default_visibility = ["//visibility:public"])

cc_library(
    name = "html_parser",
    srcs = ["html_parser.cc"],
    hdrs = ["html_parser.h"],
    deps = [
        "@com_google_absl//absl/strings:string_view",
    ],
)
